const FALLBACK={student:{id:101,userId:"aleon",password:"password",name:"Ale Leon",balance:25},staff:{userId:"staff",password:"password",name:"Dominic Toretto"},vendor:"Frenchies",menu:[{id:991,name:"Tuna Sandwich",price:10},{id:992,name:"Pizza",price:20},{id:993,name:"Roasted Green Beans",price:6}]};
const read=(k,f=null)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
async function data(){try{const r=await fetch('apps.json');if(r.ok)return await r.json()}catch{}return FALLBACK}
function role(){return sessionStorage.getItem('cflRole')}
function guard(required){if(role()!==required){location.href='index.html';return false}return true}
function order(){return read('cflOrder',null)} function cart(){return read('cflCart',[])}
async function loginInit(d){document.querySelector('#loginForm').onsubmit=e=>{e.preventDefault();const u=userId.value.trim(),p=password.value;if(u===d.student.userId&&p===d.student.password){sessionStorage.setItem('cflRole','student');location.href='account.html'}else loginError.textContent='Invalid User ID or password. Please try again.'};document.querySelector('[data-role=staff]').onclick=()=>{sessionStorage.setItem('cflRole','staff');location.href='orders.html'}}
function accountInit(d){if(!guard('student'))return;const s=read('cflStudent',d.student),o=order();studentName.textContent=s.name;balance.textContent=Number(s.balance).toFixed(2);if(o){orderId.textContent=o.id;orderVendor.textContent=o.vendor;orderStatus.textContent=o.status}}
function menuInit(d){if(!guard('student'))return;const c=cart();function draw(){menuItems.innerHTML=d.menu.map(i=>`<div class="menu-item"><div class="food-img"></div><div><b>${i.name}</b><br>$${i.price.toFixed(2)}</div><button data-id="${i.id}">+</button></div>`).join('');const x=cart();cartRows.innerHTML=x.map(i=>`<tr><td>${i.qty}</td><td>${i.name}</td><td>$${(i.price*i.qty).toFixed(2)}</td></tr>`).join('');cartTotal.textContent=x.reduce((a,i)=>a+i.price*i.qty,0).toFixed(2);document.querySelectorAll('.menu-item button').forEach(b=>b.onclick=()=>{const i=d.menu.find(x=>x.id==b.dataset.id),a=cart(),e=a.find(x=>x.id===i.id);e?e.qty++:a.push({...i,qty:1});write('cflCart',a);draw()})}draw();placeOrder.onclick=()=>{const a=cart();if(!a.length)return alert('Select at least one item.');const total=a.reduce((s,i)=>s+i.price*i.qty,0),s=read('cflStudent',d.student);if(total>s.balance)return alert('Insufficient meal-plan balance.');const o={id:15559,vendor:d.vendor,status:'Pending',date:new Date().toLocaleDateString(),pickup:pickupTime.value,notes:'',items:a,total};write('cflOrder',o);write('cflStudent',{...s,balance:+(s.balance-total).toFixed(2)});localStorage.removeItem('cflCart');location.href='confirmation.html'}}
function confirmationInit(){if(!guard('student'))return;const o=order();if(o){confirmOrder.textContent=o.id;confirmStatus.textContent=o.status==='Ready'?'ready!':o.status.toLowerCase()+'!';confirmPickup.textContent=o.pickup}logoutBtn.onclick=()=>{sessionStorage.clear();location.href='index.html'}}
function ordersInit(d){if(!guard('staff'))return;staffName.textContent=d.staff.name;const o=order();ordersBody.innerHTML=o?`<tr><td>${o.id}</td><td><select id="status"><option>Pending</option><option>Approved</option><option>Preparing</option><option>Ready</option><option>Canceled</option></select></td><td>${o.date}</td><td>${o.pickup}</td><td><textarea id="notes">${o.notes||''}</textarea></td></tr>`:'<tr><td colspan="5">No current orders.</td></tr>';if(o){status.value=o.status;status.onchange=()=>{o.status=status.value;o.notes=notes.value;write('cflOrder',o);saveMessage.textContent=`Order #${o.id} updated to ${o.status}.`};notes.onchange=()=>{o.notes=notes.value;write('cflOrder',o)}}}
document.addEventListener('DOMContentLoaded',async()=>{const d=await data();if(!localStorage.getItem('cflStudent'))write('cflStudent',d.student);const p=document.body.dataset.page;({login:loginInit,account:accountInit,menu:menuInit,confirmation:confirmationInit,orders:ordersInit}[p]||(()=>{}))(d)});